// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4dhTg5MQr8kUOLxJ55WNIwMeKuKAUkHk',
    appId: '1:809322518585:web:dfbab21a93c8b784b795e8',
    messagingSenderId: '809322518585',
    projectId: 'quality-family',
    authDomain: 'quality-family.firebaseapp.com',
    storageBucket: 'quality-family.appspot.com',
    measurementId: 'G-VN6YPNM9HL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP8MoQXYApIF7qz5NVc9s_XJ1BktWmCUg',
    appId: '1:809322518585:android:0b8483978ada2a18b795e8',
    messagingSenderId: '809322518585',
    projectId: 'quality-family',
    storageBucket: 'quality-family.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7He4SPNEWTtAtGyK84cf9JtxM2-R2cjA',
    appId: '1:809322518585:ios:bb2c4552d24c1131b795e8',
    messagingSenderId: '809322518585',
    projectId: 'quality-family',
    storageBucket: 'quality-family.appspot.com',
    iosClientId: '809322518585-6ofcl4vdif9n44ugn4om471miie8ctff.apps.googleusercontent.com',
    iosBundleId: 'com.qfam.ios',
  );
}
